### ISSUE TITLE
Can I use this EFI FILE to esonic h61 motherboard

### ISSUE THREAD

**Issue by abirabedinkhan** [Ni-X-oN/Opencore-IvyBridge-H61-Motherboard#1]
I have pc with
CPU i5-3330 Quad core Processor with stock Intel cooler.
Esonic H61FEL-U.
Ram 16GB.
SSD
a4tech mouse and keybord 

Will it work on my pc

**Comment by Ni-X-oN** [comment]
I hope the EFI should work just give it a try. Ensure that the bios settings in motherboard is configured to support Macos. You can visit the open core website and checkout the required bios setting. If there are some errors it is better to create a new EFI by keeping this EFI as a reference.

**Comment by Ni-X-oN** [comment]
What about your gpu ? Is it having a Metal compatible gpu then only you can install Macos Mojave and above.

**Comment by abirabedinkhan** [comment]
i dont have a internal gpu
audio is bluthooth speaker
internet ethernet

**Comment by Ni-X-oN** [comment]
It is better to have a gpu or else you mac experience will be boring. You can try Nvidia Gt710 2GB gpu which is cheap and is metal compatible. Internal Gpu wont work with full acceleration.

**Comment by abirabedinkhan** [comment]
Ok I'll buy one tomorrow then I'll build hakenthos tomorrow

**Comment by abirabedinkhan** [comment]
is ethernet will work

**Comment by Ni-X-oN** [comment]
Before you purchase the GPU make sure you have complete information about
you motherboard internals like audio codec, ethernet chip (You can obtain
these information from Motherboard manufacture website or any other
reference material from internet).
After identifying those information Check whether the kexts are available
for each from Opencore website. After ensuring all these purchase a GPU so
that you won't waste money.

**Comment by abirabedinkhan** [comment]
![Screenshot 2022-01-21 130316](https://user-images.githubusercontent.com/67215274/150481801-a935071b-be2c-4227-b986-fdeec5b0e591.png)
![Screenshot 2022-01-21 130337](https://user-images.githubusercontent.com/67215274/150481808-a3de7904-4304-4f20-b41a-cfb49982b55c.png)
Can u give a check for me..... plz......

**Comment by Ni-X-oN** [comment]
From this I can't see any audio codec or ethernet info. You may use speccy
tool or check online resource which I have mentioned previously.

**Comment by abirabedinkhan** [comment]
Ethernet - realtek pcie fe family controller
audio - Realtek* High Definition Audio

**Comment by Ni-X-oN** [comment]
This is a generic information wr need exact info about the chip being used.

**Comment by abirabedinkhan** [comment]
How can I get those info???

**Comment by abirabedinkhan** [comment]
CAN U GIVE ME ANY SOFTWARE WHICH WILL CHECK FOR ME??

**Comment by abirabedinkhan** [comment]
CPU(Processor) -Intel® Socket 1155 Core™ i7/Core™ i5/Core™ i3 Processors
Supports Intel® Dynamic Speed Technology
Supports Intel® 32 nm CPU
Chipset -Intel® H61(B3)
Memory -Support Dual channel DDR3 1333/1066 SDRAM (8GB Max)
2 * DDR3 DIMMs (240 pin/ 1.5V)
Slots - 1 * PCI Express x16 Slot - 1 * PCI Express x1 Slot
Storage - 4* Serial ATA 2.0 devices
Internal I/O Connectors
1 * 24-pin ATX Power Connetor
1 * 4-pin ATX 12V Power Connetor
2 * USB connector support additional 4 USB ports
1 * LPC_DEBUG connector
1 * Front panel audio connector
1 * System Panel connector
Back Panel I/O Ports – 1 * PS/2 Mouse/Keyboard
1 * VGA
1 * COM
4 * USB 2.0 / 1.1
1 * RJ45(LAN) Port
1 * 3 Audio jacks
BIOS -EFI BIOS
LAN -On board Realtek 8105E 1000M LAN, Compliance with PCI 2.2
Audio -Chip integrated by Realtek ALC662, Supports 5.1-channel audio-out

**Comment by abirabedinkhan** [comment]
LAN -On board Realtek 8105E 1000M LAN, Compliance with PCI 2.2
Audio -Chip integrated by Realtek ALC662, Supports 5.1-channel audio-out

**Comment by Ni-X-oN** [comment]
Yes both Audio and ethernet is supported. For audio use applealc kext and
ethernet use RTL8100 ver 2.0.1 kext

**Comment by abirabedinkhan** [comment]
In your reademe.md file u worte upto 8 gm ram is supported but my pc has 16 gb am than what i will do

**Comment by Ni-X-oN** [comment]
The pc was having 4Gb + 2Gb combination earlier later it was changed to 4Gb
+ 4Gb so I mentioned like 8Gb. You have 16Gb that's not a problem it is
actually good.

**Comment by abirabedinkhan** [comment]
OOhhh.Then can i start making hakenthosh??
Do you have any tutorial to follow making hackenthosh???

**Comment by Ni-X-oN** [comment]
Yes, of course you can. You can use dhananjay bhosle's hackintosh tutorial
video as a reference.

**Comment by abirabedinkhan** [comment]
is bluethooth will work

**Comment by abirabedinkhan** [comment]
do u have discord???

**Comment by Ni-X-oN** [comment]
Not sure about bluetooth support in Macos and I don't have discord.

**Comment by Ni-X-oN** [comment]
May be you can check you bluetooth model support with macos

**Comment by abirabedinkhan** [comment]
dhananjay bhosle's hackintosh tutorial is kinda hard

**Comment by Ni-X-oN** [comment]
Even though it is lengthy it is very well explained. May be you can search
other installation tutorials. Don't use Distros like Niresh. One place may
be you can visit is Olarila forum there tutorial is also fine.

**Comment by abirabedinkhan** [comment]
Do i need to replace old efi with this one???

**Comment by Ni-X-oN** [comment]
If you already had a working efi you keep using it or else you can use this
one

**Comment by abirabedinkhan** [comment]
okkk! I will keep u update

**Comment by abirabedinkhan** [comment]
It dosen't works

**Comment by Ni-X-oN** [comment]
You need tweak the efi to support your system. In the readme I have mentioned that it works on Gigabyte H61 motherboard. For other H61 based motherboards new EFI can be built using the published EFI file.

**Comment by Ni-X-oN** [comment]
The efi is not updated to the latest version of Opencore. I request everyone to keep this as a reference and build a new EFI by following OpenCore guide.
